/**
 * Byte layout of the single-file fixtures: where each init prefix and segment
 * sits in the signed file. Generated by test/assets/single-file/README.md's
 * script; regenerate rather than edit.
 */
export const singleFileLayout = {
  "solo-360p": {
    "init": "solo-360p.init.mp4",
    "initLength": 14948,
    "segments": [
      {
        "file": "solo-360p.seg00.m4s",
        "offset": 14948,
        "length": 33972
      },
      {
        "file": "solo-360p.seg01.m4s",
        "offset": 48920,
        "length": 33793
      },
      {
        "file": "solo-360p.seg02.m4s",
        "offset": 82713,
        "length": 37971
      },
      {
        "file": "solo-360p.seg03.m4s",
        "offset": 120684,
        "length": 40844
      },
      {
        "file": "solo-360p.seg04.m4s",
        "offset": 161528,
        "length": 36742
      },
      {
        "file": "solo-360p.seg05.m4s",
        "offset": 198270,
        "length": 35431
      },
      {
        "file": "solo-360p.seg06.m4s",
        "offset": 233701,
        "length": 40109
      },
      {
        "file": "solo-360p.seg07.m4s",
        "offset": 273810,
        "length": 40586
      }
    ],
    "sidxCutOfSegment1": {
      "offset": 48868,
      "length": 33793
    }
  },
  "ladder-360p": {
    "init": "ladder-360p.init.mp4",
    "initLength": 15309,
    "segments": [
      {
        "file": "ladder-360p.seg00.m4s",
        "offset": 15309,
        "length": 33972
      },
      {
        "file": "ladder-360p.seg01.m4s",
        "offset": 49281,
        "length": 33793
      },
      {
        "file": "ladder-360p.seg02.m4s",
        "offset": 83074,
        "length": 37971
      },
      {
        "file": "ladder-360p.seg03.m4s",
        "offset": 121045,
        "length": 40844
      },
      {
        "file": "ladder-360p.seg04.m4s",
        "offset": 161889,
        "length": 36742
      },
      {
        "file": "ladder-360p.seg05.m4s",
        "offset": 198631,
        "length": 35431
      },
      {
        "file": "ladder-360p.seg06.m4s",
        "offset": 234062,
        "length": 40109
      },
      {
        "file": "ladder-360p.seg07.m4s",
        "offset": 274171,
        "length": 40586
      }
    ],
    "sidxCutOfSegment1": {
      "offset": 49229,
      "length": 33793
    }
  },
  "ladder-180p": {
    "init": "ladder-180p.init.mp4",
    "initLength": 15309,
    "segments": [
      {
        "file": "ladder-180p.seg00.m4s",
        "offset": 15309,
        "length": 17223
      },
      {
        "file": "ladder-180p.seg01.m4s",
        "offset": 32532,
        "length": 17203
      },
      {
        "file": "ladder-180p.seg02.m4s",
        "offset": 49735,
        "length": 19908
      },
      {
        "file": "ladder-180p.seg03.m4s",
        "offset": 69643,
        "length": 19716
      },
      {
        "file": "ladder-180p.seg04.m4s",
        "offset": 89359,
        "length": 19804
      },
      {
        "file": "ladder-180p.seg05.m4s",
        "offset": 109163,
        "length": 18409
      },
      {
        "file": "ladder-180p.seg06.m4s",
        "offset": 127572,
        "length": 20905
      },
      {
        "file": "ladder-180p.seg07.m4s",
        "offset": 148477,
        "length": 19206
      }
    ],
    "sidxCutOfSegment1": {
      "offset": 32480,
      "length": 17203
    }
  }
} as const;
